[project]
name = "win32more-Microsoft.Graphics.Win2D"
version = "0.8.1.2.0"
dependencies = ["win32more-core==0.8.*", "win32more-Microsoft.WindowsAppSDK>=0.8.1.5.240227000,<0.9"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
