[project]
name = "win32more-Microsoft.Web.WebView2"
version = "0.8.1.0.2903.40"
dependencies = ["win32more-core==0.8.*"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
