[project]
name = "win32more-Microsoft.WindowsAppSDK"
version = "0.6.1.7.250513003"
dependencies = ["win32more==0.6.*", "win32more-Microsoft.Web.WebView2>=0.6.1.0.2903.40,<0.7"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
