[project]
name = "win32more-Microsoft.WindowsAppSDK"
version = "0.7.1.7.251107005"
dependencies = ["win32more-core==0.7.*", "win32more-Microsoft.Web.WebView2>=0.7.1.0.2903.40,<0.8"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
