[project]
name = "win32more-core"
version = "0.6.3"
dependencies = []

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
