[project]
name = "win32more-Microsoft.WindowsAppSDK"
version = "0.8.1.8.250916003"
dependencies = ["win32more-core==0.8.*", "win32more-Microsoft.Web.WebView2>=0.8.1.0.3179.45,<0.9"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
