[project]
name = "win32more-Microsoft.Windows.SDK.Win32Metadata"
version = "0.8.69.0.7"
dependencies = ["win32more-core==0.8.*"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
