[project]
name = "win32more-Microsoft.Windows.SDK.Contracts"
version = "0.6.10.0.26100.4948"
dependencies = ["win32more==0.6.*"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/win32more"]
